// <auto-generated />
namespace Moneta.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GrupoLancamento_Nav_Entre_GrupoPai_e_Filhos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GrupoLancamento_Nav_Entre_GrupoPai_e_Filhos));
        
        string IMigrationMetadata.Id
        {
            get { return "201705181620177_GrupoLancamento_Nav_Entre_GrupoPai_e_Filhos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
